language: go
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.61.0/hugo_extended_0.61.0_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.61.0_Linux-64bit.deb
script:
  - hugo 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: public
  on:
    branch: master
